using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace MetaFac.Standard.ISO4217
{
    /// <summary>
    /// Currency codes defined by ISO 4217 at https://www.iso.org/iso-4217-currency-codes.html
    /// Descriptive information is obtained from https://en.wikipedia.org/wiki/ISO_4217
    /// XML data from https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml
    /// </summary>
    public static class Iso4217Helper
    {
        /// <summary>
        /// The list of currency records.
        /// </summary>
        public static ImmutableList<Iso4217Info> Codes { get; }

        static Iso4217Helper()
        {
            Codes = ImmutableList<Iso4217Info>.Empty.AddRange(new List<Iso4217Info>
            {
                new Iso4217Info(971, "AFN", "Afghani", "AFGHANISTAN", 2),
                new Iso4217Info(978, "EUR", "Euro", "ÅLAND ISLANDS", 2),
                new Iso4217Info(008, "ALL", "Lek", "ALBANIA", 2),
                new Iso4217Info(012, "DZD", "Algerian Dinar", "ALGERIA", 2),
                new Iso4217Info(840, "USD", "US Dollar", "AMERICAN SAMOA", 2),
                new Iso4217Info(978, "EUR", "Euro", "ANDORRA", 2),
                new Iso4217Info(973, "AOA", "Kwanza", "ANGOLA", 2),
                new Iso4217Info(951, "XCD", "East Caribbean Dollar", "ANGUILLA", 2),
                new Iso4217Info(000, "", "No universal currency", "ANTARCTICA", null),
                new Iso4217Info(951, "XCD", "East Caribbean Dollar", "ANTIGUA AND BARBUDA", 2),
                new Iso4217Info(396, "XAD", "Arab Accounting Dinar", "ARAB MONETARY FUND", 2),
                new Iso4217Info(032, "ARS", "Argentine Peso", "ARGENTINA", 2),
                new Iso4217Info(051, "AMD", "Armenian Dram", "ARMENIA", 2),
                new Iso4217Info(533, "AWG", "Aruban Florin", "ARUBA", 2),
                new Iso4217Info(036, "AUD", "Australian Dollar", "AUSTRALIA", 2),
                new Iso4217Info(978, "EUR", "Euro", "AUSTRIA", 2),
                new Iso4217Info(944, "AZN", "Azerbaijan Manat", "AZERBAIJAN", 2),
                new Iso4217Info(044, "BSD", "Bahamian Dollar", "BAHAMAS (THE)", 2),
                new Iso4217Info(048, "BHD", "Bahraini Dinar", "BAHRAIN", 3),
                new Iso4217Info(050, "BDT", "Taka", "BANGLADESH", 2),
                new Iso4217Info(052, "BBD", "Barbados Dollar", "BARBADOS", 2),
                new Iso4217Info(933, "BYN", "Belarusian Ruble", "BELARUS", 2),
                new Iso4217Info(978, "EUR", "Euro", "BELGIUM", 2),
                new Iso4217Info(084, "BZD", "Belize Dollar", "BELIZE", 2),
                new Iso4217Info(952, "XOF", "CFA Franc BCEAO", "BENIN", 0),
                new Iso4217Info(060, "BMD", "Bermudian Dollar", "BERMUDA", 2),
                new Iso4217Info(356, "INR", "Indian Rupee", "BHUTAN", 2),
                new Iso4217Info(064, "BTN", "Ngultrum", "BHUTAN", 2),
                new Iso4217Info(068, "BOB", "Boliviano", "BOLIVIA (PLURINATIONAL STATE OF)", 2),
                new Iso4217Info(984, "BOV", "Mvdol", "BOLIVIA (PLURINATIONAL STATE OF)", 2),
                new Iso4217Info(840, "USD", "US Dollar", "BONAIRE, SINT EUSTATIUS AND SABA", 2),
                new Iso4217Info(977, "BAM", "Convertible Mark", "BOSNIA AND HERZEGOVINA", 2),
                new Iso4217Info(072, "BWP", "Pula", "BOTSWANA", 2),
                new Iso4217Info(578, "NOK", "Norwegian Krone", "BOUVET ISLAND", 2),
                new Iso4217Info(986, "BRL", "Brazilian Real", "BRAZIL", 2),
                new Iso4217Info(840, "USD", "US Dollar", "BRITISH INDIAN OCEAN TERRITORY (THE)", 2),
                new Iso4217Info(096, "BND", "Brunei Dollar", "BRUNEI DARUSSALAM", 2),
                new Iso4217Info(978, "EUR", "Euro", "BULGARIA", 2),
                new Iso4217Info(952, "XOF", "CFA Franc BCEAO", "BURKINA FASO", 0),
                new Iso4217Info(108, "BIF", "Burundi Franc", "BURUNDI", 0),
                new Iso4217Info(132, "CVE", "Cabo Verde Escudo", "CABO VERDE", 2),
                new Iso4217Info(116, "KHR", "Riel", "CAMBODIA", 2),
                new Iso4217Info(950, "XAF", "CFA Franc BEAC", "CAMEROON", 0),
                new Iso4217Info(124, "CAD", "Canadian Dollar", "CANADA", 2),
                new Iso4217Info(136, "KYD", "Cayman Islands Dollar", "CAYMAN ISLANDS (THE)", 2),
                new Iso4217Info(950, "XAF", "CFA Franc BEAC", "CENTRAL AFRICAN REPUBLIC (THE)", 0),
                new Iso4217Info(950, "XAF", "CFA Franc BEAC", "CHAD", 0),
                new Iso4217Info(152, "CLP", "Chilean Peso", "CHILE", 0),
                new Iso4217Info(990, "CLF", "Unidad de Fomento", "CHILE", 4),
                new Iso4217Info(156, "CNY", "Yuan Renminbi", "CHINA", 2),
                new Iso4217Info(036, "AUD", "Australian Dollar", "CHRISTMAS ISLAND", 2),
                new Iso4217Info(036, "AUD", "Australian Dollar", "COCOS (KEELING) ISLANDS (THE)", 2),
                new Iso4217Info(170, "COP", "Colombian Peso", "COLOMBIA", 2),
                new Iso4217Info(970, "COU", "Unidad de Valor Real", "COLOMBIA", 2),
                new Iso4217Info(174, "KMF", "Comorian Franc ", "COMOROS (THE)", 0),
                new Iso4217Info(976, "CDF", "Congolese Franc", "CONGO (THE DEMOCRATIC REPUBLIC OF THE)", 2),
                new Iso4217Info(950, "XAF", "CFA Franc BEAC", "CONGO (THE)", 0),
                new Iso4217Info(554, "NZD", "New Zealand Dollar", "COOK ISLANDS (THE)", 2),
                new Iso4217Info(188, "CRC", "Costa Rican Colon", "COSTA RICA", 2),
                new Iso4217Info(952, "XOF", "CFA Franc BCEAO", "CÔTE D'IVOIRE", 0),
                new Iso4217Info(978, "EUR", "Euro", "CROATIA", 2),
                new Iso4217Info(192, "CUP", "Cuban Peso", "CUBA", 2),
                new Iso4217Info(532, "XCG", "Caribbean Guilder", "CURAÇAO", 2),
                new Iso4217Info(978, "EUR", "Euro", "CYPRUS", 2),
                new Iso4217Info(203, "CZK", "Czech Koruna", "CZECHIA", 2),
                new Iso4217Info(208, "DKK", "Danish Krone", "DENMARK", 2),
                new Iso4217Info(262, "DJF", "Djibouti Franc", "DJIBOUTI", 0),
                new Iso4217Info(951, "XCD", "East Caribbean Dollar", "DOMINICA", 2),
                new Iso4217Info(214, "DOP", "Dominican Peso", "DOMINICAN REPUBLIC (THE)", 2),
                new Iso4217Info(840, "USD", "US Dollar", "ECUADOR", 2),
                new Iso4217Info(818, "EGP", "Egyptian Pound", "EGYPT", 2),
                new Iso4217Info(222, "SVC", "El Salvador Colon", "EL SALVADOR", 2),
                new Iso4217Info(840, "USD", "US Dollar", "EL SALVADOR", 2),
                new Iso4217Info(950, "XAF", "CFA Franc BEAC", "EQUATORIAL GUINEA", 0),
                new Iso4217Info(232, "ERN", "Nakfa", "ERITREA", 2),
                new Iso4217Info(978, "EUR", "Euro", "ESTONIA", 2),
                new Iso4217Info(230, "ETB", "Ethiopian Birr", "ETHIOPIA", 2),
                new Iso4217Info(978, "EUR", "Euro", "EUROPEAN UNION", 2),
                new Iso4217Info(238, "FKP", "Falkland Islands Pound", "FALKLAND ISLANDS (THE) [MALVINAS]", 2),
                new Iso4217Info(208, "DKK", "Danish Krone", "FAROE ISLANDS (THE)", 2),
                new Iso4217Info(242, "FJD", "Fiji Dollar", "FIJI", 2),
                new Iso4217Info(978, "EUR", "Euro", "FINLAND", 2),
                new Iso4217Info(978, "EUR", "Euro", "FRANCE", 2),
                new Iso4217Info(978, "EUR", "Euro", "FRENCH GUIANA", 2),
                new Iso4217Info(953, "XPF", "CFP Franc", "FRENCH POLYNESIA", 0),
                new Iso4217Info(978, "EUR", "Euro", "FRENCH SOUTHERN TERRITORIES (THE)", 2),
                new Iso4217Info(950, "XAF", "CFA Franc BEAC", "GABON", 0),
                new Iso4217Info(270, "GMD", "Dalasi", "GAMBIA (THE)", 2),
                new Iso4217Info(981, "GEL", "Lari", "GEORGIA", 2),
                new Iso4217Info(978, "EUR", "Euro", "GERMANY", 2),
                new Iso4217Info(936, "GHS", "Ghana Cedi", "GHANA", 2),
                new Iso4217Info(292, "GIP", "Gibraltar Pound", "GIBRALTAR", 2),
                new Iso4217Info(978, "EUR", "Euro", "GREECE", 2),
                new Iso4217Info(208, "DKK", "Danish Krone", "GREENLAND", 2),
                new Iso4217Info(951, "XCD", "East Caribbean Dollar", "GRENADA", 2),
                new Iso4217Info(978, "EUR", "Euro", "GUADELOUPE", 2),
                new Iso4217Info(840, "USD", "US Dollar", "GUAM", 2),
                new Iso4217Info(320, "GTQ", "Quetzal", "GUATEMALA", 2),
                new Iso4217Info(826, "GBP", "Pound Sterling", "GUERNSEY", 2),
                new Iso4217Info(324, "GNF", "Guinean Franc", "GUINEA", 0),
                new Iso4217Info(952, "XOF", "CFA Franc BCEAO", "GUINEA-BISSAU", 0),
                new Iso4217Info(328, "GYD", "Guyana Dollar", "GUYANA", 2),
                new Iso4217Info(332, "HTG", "Gourde", "HAITI", 2),
                new Iso4217Info(840, "USD", "US Dollar", "HAITI", 2),
                new Iso4217Info(036, "AUD", "Australian Dollar", "HEARD ISLAND AND McDONALD ISLANDS", 2),
                new Iso4217Info(978, "EUR", "Euro", "HOLY SEE (THE)", 2),
                new Iso4217Info(340, "HNL", "Lempira", "HONDURAS", 2),
                new Iso4217Info(344, "HKD", "Hong Kong Dollar", "HONG KONG", 2),
                new Iso4217Info(348, "HUF", "Forint", "HUNGARY", 2),
                new Iso4217Info(352, "ISK", "Iceland Krona", "ICELAND", 0),
                new Iso4217Info(356, "INR", "Indian Rupee", "INDIA", 2),
                new Iso4217Info(360, "IDR", "Rupiah", "INDONESIA", 2),
                new Iso4217Info(960, "XDR", "SDR (Special Drawing Right)", "INTERNATIONAL MONETARY FUND (IMF) ", null),
                new Iso4217Info(364, "IRR", "Iranian Rial", "IRAN (ISLAMIC REPUBLIC OF)", 2),
                new Iso4217Info(368, "IQD", "Iraqi Dinar", "IRAQ", 3),
                new Iso4217Info(978, "EUR", "Euro", "IRELAND", 2),
                new Iso4217Info(826, "GBP", "Pound Sterling", "ISLE OF MAN", 2),
                new Iso4217Info(376, "ILS", "New Israeli Sheqel", "ISRAEL", 2),
                new Iso4217Info(978, "EUR", "Euro", "ITALY", 2),
                new Iso4217Info(388, "JMD", "Jamaican Dollar", "JAMAICA", 2),
                new Iso4217Info(392, "JPY", "Yen", "JAPAN", 0),
                new Iso4217Info(826, "GBP", "Pound Sterling", "JERSEY", 2),
                new Iso4217Info(400, "JOD", "Jordanian Dinar", "JORDAN", 3),
                new Iso4217Info(398, "KZT", "Tenge", "KAZAKHSTAN", 2),
                new Iso4217Info(404, "KES", "Kenyan Shilling", "KENYA", 2),
                new Iso4217Info(036, "AUD", "Australian Dollar", "KIRIBATI", 2),
                new Iso4217Info(408, "KPW", "North Korean Won", "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)", 2),
                new Iso4217Info(410, "KRW", "Won", "KOREA (THE REPUBLIC OF)", 0),
                new Iso4217Info(414, "KWD", "Kuwaiti Dinar", "KUWAIT", 3),
                new Iso4217Info(417, "KGS", "Som", "KYRGYZSTAN", 2),
                new Iso4217Info(418, "LAK", "Lao Kip", "LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)", 2),
                new Iso4217Info(978, "EUR", "Euro", "LATVIA", 2),
                new Iso4217Info(422, "LBP", "Lebanese Pound", "LEBANON", 2),
                new Iso4217Info(426, "LSL", "Loti", "LESOTHO", 2),
                new Iso4217Info(710, "ZAR", "Rand", "LESOTHO", 2),
                new Iso4217Info(430, "LRD", "Liberian Dollar", "LIBERIA", 2),
                new Iso4217Info(434, "LYD", "Libyan Dinar", "LIBYA", 3),
                new Iso4217Info(756, "CHF", "Swiss Franc", "LIECHTENSTEIN", 2),
                new Iso4217Info(978, "EUR", "Euro", "LITHUANIA", 2),
                new Iso4217Info(978, "EUR", "Euro", "LUXEMBOURG", 2),
                new Iso4217Info(446, "MOP", "Pataca", "MACAO", 2),
                new Iso4217Info(807, "MKD", "Denar", "MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)", 2),
                new Iso4217Info(969, "MGA", "Malagasy Ariary", "MADAGASCAR", 2),
                new Iso4217Info(454, "MWK", "Malawi Kwacha", "MALAWI", 2),
                new Iso4217Info(458, "MYR", "Malaysian Ringgit", "MALAYSIA", 2),
                new Iso4217Info(462, "MVR", "Rufiyaa", "MALDIVES", 2),
                new Iso4217Info(952, "XOF", "CFA Franc BCEAO", "MALI", 0),
                new Iso4217Info(978, "EUR", "Euro", "MALTA", 2),
                new Iso4217Info(840, "USD", "US Dollar", "MARSHALL ISLANDS (THE)", 2),
                new Iso4217Info(978, "EUR", "Euro", "MARTINIQUE", 2),
                new Iso4217Info(929, "MRU", "Ouguiya", "MAURITANIA", 2),
                new Iso4217Info(480, "MUR", "Mauritius Rupee", "MAURITIUS", 2),
                new Iso4217Info(978, "EUR", "Euro", "MAYOTTE", 2),
                new Iso4217Info(965, "XUA", "ADB Unit of Account", "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP", null),
                new Iso4217Info(484, "MXN", "Mexican Peso", "MEXICO", 2),
                new Iso4217Info(979, "MXV", "Mexican Unidad de Inversion (UDI)", "MEXICO", 2),
                new Iso4217Info(840, "USD", "US Dollar", "MICRONESIA (FEDERATED STATES OF)", 2),
                new Iso4217Info(498, "MDL", "Moldovan Leu", "MOLDOVA (THE REPUBLIC OF)", 2),
                new Iso4217Info(978, "EUR", "Euro", "MONACO", 2),
                new Iso4217Info(496, "MNT", "Tugrik", "MONGOLIA", 2),
                new Iso4217Info(978, "EUR", "Euro", "MONTENEGRO", 2),
                new Iso4217Info(951, "XCD", "East Caribbean Dollar", "MONTSERRAT", 2),
                new Iso4217Info(504, "MAD", "Moroccan Dirham", "MOROCCO", 2),
                new Iso4217Info(943, "MZN", "Mozambique Metical", "MOZAMBIQUE", 2),
                new Iso4217Info(104, "MMK", "Kyat", "MYANMAR", 2),
                new Iso4217Info(516, "NAD", "Namibia Dollar", "NAMIBIA", 2),
                new Iso4217Info(710, "ZAR", "Rand", "NAMIBIA", 2),
                new Iso4217Info(036, "AUD", "Australian Dollar", "NAURU", 2),
                new Iso4217Info(524, "NPR", "Nepalese Rupee", "NEPAL", 2),
                new Iso4217Info(978, "EUR", "Euro", "NETHERLANDS (THE)", 2),
                new Iso4217Info(953, "XPF", "CFP Franc", "NEW CALEDONIA", 0),
                new Iso4217Info(554, "NZD", "New Zealand Dollar", "NEW ZEALAND", 2),
                new Iso4217Info(558, "NIO", "Cordoba Oro", "NICARAGUA", 2),
                new Iso4217Info(952, "XOF", "CFA Franc BCEAO", "NIGER (THE)", 0),
                new Iso4217Info(566, "NGN", "Naira", "NIGERIA", 2),
                new Iso4217Info(554, "NZD", "New Zealand Dollar", "NIUE", 2),
                new Iso4217Info(036, "AUD", "Australian Dollar", "NORFOLK ISLAND", 2),
                new Iso4217Info(840, "USD", "US Dollar", "NORTHERN MARIANA ISLANDS (THE)", 2),
                new Iso4217Info(578, "NOK", "Norwegian Krone", "NORWAY", 2),
                new Iso4217Info(512, "OMR", "Rial Omani", "OMAN", 3),
                new Iso4217Info(586, "PKR", "Pakistan Rupee", "PAKISTAN", 2),
                new Iso4217Info(840, "USD", "US Dollar", "PALAU", 2),
                new Iso4217Info(000, "", "No universal currency", "PALESTINE, STATE OF", null),
                new Iso4217Info(590, "PAB", "Balboa", "PANAMA", 2),
                new Iso4217Info(840, "USD", "US Dollar", "PANAMA", 2),
                new Iso4217Info(598, "PGK", "Kina", "PAPUA NEW GUINEA", 2),
                new Iso4217Info(600, "PYG", "Guarani", "PARAGUAY", 0),
                new Iso4217Info(604, "PEN", "Sol", "PERU", 2),
                new Iso4217Info(608, "PHP", "Philippine Peso", "PHILIPPINES (THE)", 2),
                new Iso4217Info(554, "NZD", "New Zealand Dollar", "PITCAIRN", 2),
                new Iso4217Info(985, "PLN", "Zloty", "POLAND", 2),
                new Iso4217Info(978, "EUR", "Euro", "PORTUGAL", 2),
                new Iso4217Info(840, "USD", "US Dollar", "PUERTO RICO", 2),
                new Iso4217Info(634, "QAR", "Qatari Rial", "QATAR", 2),
                new Iso4217Info(978, "EUR", "Euro", "RÉUNION", 2),
                new Iso4217Info(946, "RON", "Romanian Leu", "ROMANIA", 2),
                new Iso4217Info(643, "RUB", "Russian Ruble", "RUSSIAN FEDERATION (THE)", 2),
                new Iso4217Info(646, "RWF", "Rwanda Franc", "RWANDA", 0),
                new Iso4217Info(978, "EUR", "Euro", "SAINT BARTHÉLEMY", 2),
                new Iso4217Info(654, "SHP", "Saint Helena Pound", "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA", 2),
                new Iso4217Info(951, "XCD", "East Caribbean Dollar", "SAINT KITTS AND NEVIS", 2),
                new Iso4217Info(951, "XCD", "East Caribbean Dollar", "SAINT LUCIA", 2),
                new Iso4217Info(978, "EUR", "Euro", "SAINT MARTIN (FRENCH PART)", 2),
                new Iso4217Info(978, "EUR", "Euro", "SAINT PIERRE AND MIQUELON", 2),
                new Iso4217Info(951, "XCD", "East Caribbean Dollar", "SAINT VINCENT AND THE GRENADINES", 2),
                new Iso4217Info(882, "WST", "Tala", "SAMOA", 2),
                new Iso4217Info(978, "EUR", "Euro", "SAN MARINO", 2),
                new Iso4217Info(930, "STN", "Dobra", "SAO TOME AND PRINCIPE", 2),
                new Iso4217Info(682, "SAR", "Saudi Riyal", "SAUDI ARABIA", 2),
                new Iso4217Info(952, "XOF", "CFA Franc BCEAO", "SENEGAL", 0),
                new Iso4217Info(941, "RSD", "Serbian Dinar", "SERBIA", 2),
                new Iso4217Info(690, "SCR", "Seychelles Rupee", "SEYCHELLES", 2),
                new Iso4217Info(925, "SLE", "Leone", "SIERRA LEONE", 2),
                new Iso4217Info(702, "SGD", "Singapore Dollar", "SINGAPORE", 2),
                new Iso4217Info(532, "XCG", "Caribbean Guilder", "SINT MAARTEN (DUTCH PART)", 2),
                new Iso4217Info(994, "XSU", "Sucre", "SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS SUCRE", null),
                new Iso4217Info(978, "EUR", "Euro", "SLOVAKIA", 2),
                new Iso4217Info(978, "EUR", "Euro", "SLOVENIA", 2),
                new Iso4217Info(090, "SBD", "Solomon Islands Dollar", "SOLOMON ISLANDS", 2),
                new Iso4217Info(706, "SOS", "Somali Shilling", "SOMALIA", 2),
                new Iso4217Info(710, "ZAR", "Rand", "SOUTH AFRICA", 2),
                new Iso4217Info(000, "", "No universal currency", "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", null),
                new Iso4217Info(728, "SSP", "South Sudanese Pound", "SOUTH SUDAN", 2),
                new Iso4217Info(978, "EUR", "Euro", "SPAIN", 2),
                new Iso4217Info(144, "LKR", "Sri Lanka Rupee", "SRI LANKA", 2),
                new Iso4217Info(938, "SDG", "Sudanese Pound", "SUDAN (THE)", 2),
                new Iso4217Info(968, "SRD", "Surinam Dollar", "SURINAME", 2),
                new Iso4217Info(578, "NOK", "Norwegian Krone", "SVALBARD AND JAN MAYEN", 2),
                new Iso4217Info(748, "SZL", "Lilangeni", "ESWATINI", 2),
                new Iso4217Info(752, "SEK", "Swedish Krona", "SWEDEN", 2),
                new Iso4217Info(756, "CHF", "Swiss Franc", "SWITZERLAND", 2),
                new Iso4217Info(947, "CHE", "WIR Euro", "SWITZERLAND", 2),
                new Iso4217Info(948, "CHW", "WIR Franc", "SWITZERLAND", 2),
                new Iso4217Info(760, "SYP", "Syrian Pound", "SYRIAN ARAB REPUBLIC", 2),
                new Iso4217Info(901, "TWD", "New Taiwan Dollar", "TAIWAN (PROVINCE OF CHINA)", 2),
                new Iso4217Info(972, "TJS", "Somoni", "TAJIKISTAN", 2),
                new Iso4217Info(834, "TZS", "Tanzanian Shilling", "TANZANIA, UNITED REPUBLIC OF", 2),
                new Iso4217Info(764, "THB", "Baht", "THAILAND", 2),
                new Iso4217Info(840, "USD", "US Dollar", "TIMOR-LESTE", 2),
                new Iso4217Info(952, "XOF", "CFA Franc BCEAO", "TOGO", 0),
                new Iso4217Info(554, "NZD", "New Zealand Dollar", "TOKELAU", 2),
                new Iso4217Info(776, "TOP", "Pa’anga", "TONGA", 2),
                new Iso4217Info(780, "TTD", "Trinidad and Tobago Dollar", "TRINIDAD AND TOBAGO", 2),
                new Iso4217Info(788, "TND", "Tunisian Dinar", "TUNISIA", 3),
                new Iso4217Info(949, "TRY", "Turkish Lira", "TÜRKİYE", 2),
                new Iso4217Info(934, "TMT", "Turkmenistan New Manat", "TURKMENISTAN", 2),
                new Iso4217Info(840, "USD", "US Dollar", "TURKS AND CAICOS ISLANDS (THE)", 2),
                new Iso4217Info(036, "AUD", "Australian Dollar", "TUVALU", 2),
                new Iso4217Info(800, "UGX", "Uganda Shilling", "UGANDA", 0),
                new Iso4217Info(980, "UAH", "Hryvnia", "UKRAINE", 2),
                new Iso4217Info(784, "AED", "UAE Dirham", "UNITED ARAB EMIRATES (THE)", 2),
                new Iso4217Info(826, "GBP", "Pound Sterling", "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)", 2),
                new Iso4217Info(840, "USD", "US Dollar", "UNITED STATES MINOR OUTLYING ISLANDS (THE)", 2),
                new Iso4217Info(840, "USD", "US Dollar", "UNITED STATES OF AMERICA (THE)", 2),
                new Iso4217Info(997, "USN", "US Dollar (Next day)", "UNITED STATES OF AMERICA (THE)", 2),
                new Iso4217Info(858, "UYU", "Peso Uruguayo", "URUGUAY", 2),
                new Iso4217Info(940, "UYI", "Uruguay Peso en Unidades Indexadas (UI)", "URUGUAY", 0),
                new Iso4217Info(927, "UYW", "Unidad Previsional", "URUGUAY", 4),
                new Iso4217Info(860, "UZS", "Uzbekistan Sum", "UZBEKISTAN", 2),
                new Iso4217Info(548, "VUV", "Vatu", "VANUATU", 0),
                new Iso4217Info(928, "VES", "Bolívar Soberano", "VENEZUELA (BOLIVARIAN REPUBLIC OF)", 2),
                new Iso4217Info(704, "VND", "Dong", "VIET NAM", 0),
                new Iso4217Info(840, "USD", "US Dollar", "VIRGIN ISLANDS (BRITISH)", 2),
                new Iso4217Info(840, "USD", "US Dollar", "VIRGIN ISLANDS (U.S.)", 2),
                new Iso4217Info(953, "XPF", "CFP Franc", "WALLIS AND FUTUNA", 0),
                new Iso4217Info(504, "MAD", "Moroccan Dirham", "WESTERN SAHARA", 2),
                new Iso4217Info(886, "YER", "Yemeni Rial", "YEMEN", 2),
                new Iso4217Info(967, "ZMW", "Zambian Kwacha", "ZAMBIA", 2),
                new Iso4217Info(924, "ZWG", "Zimbabwe Gold", "ZIMBABWE", 2),
                new Iso4217Info(955, "XBA", "Bond Markets Unit European Composite Unit (EURCO)", "ZZ01_Bond Markets Unit European_EURCO", null),
                new Iso4217Info(956, "XBB", "Bond Markets Unit European Monetary Unit (E.M.U.-6)", "ZZ02_Bond Markets Unit European_EMU-6", null),
                new Iso4217Info(957, "XBC", "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", "ZZ03_Bond Markets Unit European_EUA-9", null),
                new Iso4217Info(958, "XBD", "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", "ZZ04_Bond Markets Unit European_EUA-17", null),
                new Iso4217Info(963, "XTS", "Codes specifically reserved for testing purposes", "ZZ06_Testing_Code", null),
                new Iso4217Info(999, "XXX", "The codes assigned for transactions where no currency is involved", "ZZ07_No_Currency", null),
                new Iso4217Info(959, "XAU", "Gold", "ZZ08_Gold", null),
                new Iso4217Info(964, "XPD", "Palladium", "ZZ09_Palladium", null),
                new Iso4217Info(962, "XPT", "Platinum", "ZZ10_Platinum", null),
                new Iso4217Info(961, "XAG", "Silver", "ZZ11_Silver", null)
            });
        }

        /// <summary>
        /// Finds all currency records matching the 3-character code.
        /// </summary>
        /// <param name="code"></param>
        /// <returns></returns>
        public static IEnumerable<Iso4217Info> GetAllByCode(string? code)
        {
            return Codes.Where(x => x.Code.Equals(code, StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>
        /// Finds all currency records matching the 3-digit number.
        /// </summary>
        /// <param name="num"></param>
        /// <returns></returns>
        public static IEnumerable<Iso4217Info> GetAllByNum(int num)
        {
            return Codes.Where(x => x.Num == num);
        }

    }
}